project_id = "jyimtfbfntikeugqumxb"

[functions.send-email]
verify_jwt = false

[functions.analyze-roi-data]
verify_jwt = false

[functions.book-appointment]
verify_jwt = false

[functions.send-contact-message]
verify_jwt = false