project_id = "jyimtfbfntikeugqumxb"

[functions.send-roi-email]
verify_jwt = false

[functions.analyze-roi-data]
verify_jwt = false

[functions.book-appointment]
verify_jwt = false

[functions.send-contact-message]
verify_jwt = false

[functions.test-resend]
verify_jwt = false

[functions.simple-test]
verify_jwt = false